In [1]:
import pycmap

api = pycmap.API()
pycmap.__version__

/Users/mohammad/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

'0.2.20'

In [9]:
api.query("select top 5 * from tblAltimetry_REP_Signal")

,time,lat,lon,sla,err_sla,ugosa,err_ugosa,vgosa,err_vgosa,adt,ugos,vgos,flag_ice,tpa_correction,year,month,week,dayofyear
0,1993-01-01T00:00:00,-89.875,-179.875,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0061,1993,1,53,1
1,1993-01-01T00:00:00,-89.875,-179.625,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0061,1993,1,53,1
2,1993-01-01T00:00:00,-89.875,-179.375,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0061,1993,1,53,1
3,1993-01-01T00:00:00,-89.875,-179.125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0061,1993,1,53,1
4,1993-01-01T00:00:00,-89.875,-178.875,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0061,1993,1,53,1

## Colocalize
sample the target datasets at the loacations specified by the source dataset. Here, the source dataset is a cruise trajectory.

In [6]:

targets = {
            "tblAltimetry_REP_Signal": {
                                    "variables": ["sla", "adt"],
                                    "tolerances": [0, 0.25, 0.25, 5]
                                    },
            "tblDarwin_Nutrient_Climatology": {
                                    "variables": ["PO4_darwin_clim"],
                                    "tolerances": [0, 0.25, 0.25, 5]
                                    },       
            }

src_df = api.cruise_trajectory("Gradients_1")[:3]  # just a few rows for demonstration

pycmap.Sample(
              source=src_df, 
              targets=targets,
              replaceWithMonthlyClimatolog=True,
              agg_fun=["avg", "count", "stdev"]
             )

Gathering metadata ....
Sampling starts
Sampling finished

,time,lat,lon,CMAP_sla_tblAltimetry_REP_Signal_avg,CMAP_sla_tblAltimetry_REP_Signal_count,CMAP_sla_tblAltimetry_REP_Signal_std,CMAP_adt_tblAltimetry_REP_Signal_avg,CMAP_adt_tblAltimetry_REP_Signal_count,CMAP_adt_tblAltimetry_REP_Signal_std,CMAP_PO4_darwin_clim_tblDarwin_Nutrient_Climatology_avg,CMAP_PO4_darwin_clim_tblDarwin_Nutrient_Climatology_count,CMAP_PO4_darwin_clim_tblDarwin_Nutrient_Climatology_std
0,2016-04-20T00:04:37,21.4542,-158.3111,0.1374,4.0,0.013812,1.12955,4.0,0.017069,0.002989,1.0,NaN
1,2016-04-20T00:07:37,21.4614,-158.3132,0.1374,4.0,0.013812,1.12955,4.0,0.017069,0.002989,1.0,NaN
2,2016-04-20T00:10:37,21.4688,-158.3151,0.1374,4.0,0.013812,1.12955,4.0,0.017069,0.002989,1.0,NaN